# .drone.yml
kind: pipeline
type: docker
name: default

steps:
  - name: dockerfile-lint
    image: ghcr.io/hadolint/hadolint:latest-debian
    commands:
      - hadolint --version
      - hadolint build/Dockerfile
