# .drone.yml
kind: pipeline
type: docker
name: lint

steps:
  - name: hadolint
    image: ghcr.io/hadolint/hadolint:latest-debian
    commands:
      - hadolint --version
      - hadolint build/Dockerfile

  - name: shellcheck
    image: koalaman/shellcheck-alpine:stable
    commands:
      - shellcheck build/start.sh
